### ISSUE TITLE
Failure in EnsureLoadBalancer: missing prefix hcloud://

### ISSUE THREAD

**Issue by alexeyzimarev** [hetznercloud/hcloud-cloud-controller-manager#70] opened 2020-08-03 17:11 UTC
I have a running cluster and I have previously provisioned a load balancer using the instructions provided for the ingress controller. It all works fine.

However, now I am trying to do a similar thing for another service and I keep getting this:

> error processing service gitlabsync/production-auto-deploy-aspnetcore (will retry): failed to ensure load balancer: hcloud/loadBalancers.EnsureLoadBalancer: hcops/LoadBalancerOps.ReconcileHCLBTargets: hcops/providerIDToServerID: missing prefix hcloud://: 

I experience this issue with any new service of type LoadBalancer with hcloud annotations.

It seems some requirements have changed but it's not documented what do I suppose to do. It looks the same as #50 but I don't really want to re-provision the cluster since it works just fine and I have quite a lot of things running there.

**Comment by alexeyzimarev** [comment] 2020-08-03 17:17
I checked #52 as well and I am sure I followed the instructions from another tutorial and I have this:

```
root@master-1:/etc/systemd/system/kubelet.service.d# cat 20-hetzner-cloud.conf
[Service]
Environment="KUBELET_EXTRA_ARGS=--cloud-provider=external"
```

**Comment by LKaemmerling** [comment] 2020-08-03 18:36
Please keep in mind that you need to create the cluster with this Argument, just a restart is not enough. Actually the only way that this message can be triggered is a missing cloud provider flag on cluster creation.

**Comment by alexeyzimarev** [comment] 2020-08-03 19:01
As I mentioned before, I created the cluster according to the guidelines and I cat the file just to be sure it's there.

In addition, I also mentioned that I managed to provision one load balancer as described in the documentation about four weeks ago but suddenly it doesn't work anymore.

**Comment by LKaemmerling** [comment] 2020-08-04 04:57
Maybe there was a k8s update that removed/unloaded the setting? Actually there was no release on our side (or at least no requirement change) .

**Comment by LKaemmerling** [comment] 2020-08-25 05:00
Duplicate of #80

**Closed by LKaemmerling** 2020-08-25 05:00 UTC
Labels: duplicate

**Comment by morphace** [comment] 2021-02-01 09:40
I've got the same issue as @alexeyzimarev - although I followed the steps in the readme.md (except that I use cilium instead flannel) of  I get the same error message.

I use Ubuntu 18.04 and k8s V 1.18.5. Is there anything I can check, to verify that my config is OK?

**Comment by morphace** [comment] 2021-02-01 11:17
Just got it to work 👍 

1.) I moved to Ubuntu 20.04 and k8s 1.20
2.) I added

`[Service]
Environment="KUBELET_EXTRA_ARGS=--cloud-provider=external"` 

to the worker nodes as well (before I did it only on the master node).

I don't know which one made it work, but it works.

**Comment by MuhanedYahya** [comment] 2024-06-24 08:29
[https://github.com/kubernetes/kubeadm/issues/1021#issuecomment-408090344](url)
for me this solution worked
